trigger:
  - main

variables:
  - group: dev-cicd-grp
  - group: uat-cicd-grp
  - name: notebookPath
    value: "notebooks"  

pool: my-personal-computer

stages:
  - template: deploy.yml
    parameters:
      stageId: "Deploy_to_Dev_Env"
      env: "dev"
      environmentName: $(dev-env-name)
      resourceGroupName: $(dev-resource-grp-name)
      serviceConnection: $(dev-service-connection-name)
      notebookPath: $(notebookPath)

  - template: deploy.yml
    parameters:
      dependsOn: "Deploy_to_Dev_Env"
      stageId: "Deploy_to_UAT_Env"
      env: "UAT"
      environmentName: $(uat-env-name)
      resourceGroupName: $(uat-resource-grp-name)
      serviceConnection: $(uat-service-connection-name)
      notebookPath: $(notebookPath)
